//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Trial_session.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("Hovaten")]
    public partial class Bao : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Ha fHaID;
        [Association(@"BaoReferencesHa")]
        public Ha HaID
        {
            get { return fHaID; }
            set { SetPropertyValue<Ha>(nameof(HaID), ref fHaID, value); }
        }
        string fHovaten;
        [Size(50)]
        public string Hovaten
        {
            get { return fHovaten; }
            set { SetPropertyValue<string>(nameof(Hovaten), ref fHovaten, value); }
        }
        [Association(@"HaReferencesBao"), Aggregated]
        public XPCollection<Ha> Has { get { return GetCollection<Ha>(nameof(Has)); } }
    }

}
