//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Trial_session.Module.BusinessObjects.ORMDataModel1
{

    [DefaultProperty("ngaythangnam")]
    public partial class Ha : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Bao fBaoID;
        [Association(@"HaReferencesBao")]
        public Bao BaoID
        {
            get { return fBaoID; }
            set { SetPropertyValue<Bao>(nameof(BaoID), ref fBaoID, value); }
        }
        DateTime fngaythangnam;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime ngaythangnam
        {
            get { return fngaythangnam; }
            set { SetPropertyValue<DateTime>(nameof(ngaythangnam), ref fngaythangnam, value); }
        }
        [Association(@"BaoReferencesHa"), Aggregated]
        public XPCollection<Bao> Baos { get { return GetCollection<Bao>(nameof(Baos)); } }
    }

}
